/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlacklistEntry {
  'name' : string,
  'idNumber' : string,
  'addedAt' : bigint,
  'addedBy' : string,
  'category' : [] | [Category],
  'reason' : string,
  'companyId' : string,
}
export type Category = { 'internal' : null } |
  { 'external' : null };
export interface Company {
  'loginCode' : string,
  'name' : string,
  'createdAt' : bigint,
  'sector' : string,
  'address' : string,
  'authorizedPerson' : string,
  'companyId' : string,
}
export type Department = { 'hr' : null } |
  { 'finance' : null } |
  { 'sales' : null } |
  { 'engineering' : null };
export interface Staff {
  'staffId' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : StaffRole,
  'companyId' : string,
}
export type StaffRole = { 'admin' : null } |
  { 'security' : null };
export interface Visitor {
  'status' : VisitorStatus,
  'accessCardReturned' : boolean,
  'accessCardNumber' : [] | [string],
  'arrivalTime' : bigint,
  'departureTime' : [] | [bigint],
  'host' : string,
  'name' : string,
  'createdAt' : bigint,
  'visitorId' : bigint,
  'badgeExpired' : boolean,
  'company' : string,
  'idNumber' : string,
  'badgeQr' : string,
  'notes' : string,
  'category' : Category,
  'phone' : string,
  'photo' : [] | [Uint8Array],
  'department' : Department,
  'purpose' : string,
  'companyId' : string,
}
export type VisitorStatus = { 'active' : null } |
  { 'rejected' : null } |
  { 'departed' : null };
export interface _SERVICE {
  'addBlacklistEntry' : ActorMethod<[BlacklistEntry], undefined>,
  'addVisitor' : ActorMethod<[Visitor], undefined>,
  'getBlacklistEntries' : ActorMethod<[string], Array<BlacklistEntry>>,
  'getCompanyById' : ActorMethod<[string], [] | [Company]>,
  'getStaffByCompanyId' : ActorMethod<[string], Array<Staff>>,
  'getVisitor' : ActorMethod<[bigint], [] | [Visitor]>,
  'getVisitorsByCompany' : ActorMethod<[string], Array<Visitor>>,
  'isBlacklisted' : ActorMethod<[string, string], boolean>,
  'loginCompany' : ActorMethod<[string], [] | [Company]>,
  'loginStaff' : ActorMethod<[string, string], [] | [Staff]>,
  'registerCompany' : ActorMethod<
    [string, string, string, string, string, string],
    Company
  >,
  'registerStaff' : ActorMethod<[string, string, string, StaffRole], Staff>,
  'removeBlacklistEntry' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];