/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : string,
  'status' : AppointmentStatus,
  'noShow' : boolean,
  'hostName' : string,
  'createdAt' : bigint,
  'createdBy' : string,
  'hostStaffId' : string,
  'hostApprovalStatus' : HostApprovalStatus,
  'appointmentDate' : bigint,
  'meetingRoomId' : string,
  'visitorId' : string,
  'appointmentTime' : string,
  'visitorName' : string,
  'notes' : string,
  'purpose' : string,
  'companyId' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'approved' : null };
export interface BlacklistEntry {
  'name' : string,
  'idNumber' : string,
  'addedAt' : bigint,
  'addedBy' : string,
  'category' : string,
  'reason' : string,
  'companyId' : string,
}
export interface Company {
  'loginCode' : string,
  'name' : string,
  'createdAt' : bigint,
  'sector' : string,
  'address' : string,
  'authorizedPerson' : string,
  'companyId' : string,
}
export type HostApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Staff {
  'staffId' : string,
  'name' : string,
  'createdAt' : bigint,
  'role' : StaffRole,
  'companyId' : string,
}
export type StaffRole = { 'admin' : null } |
  { 'security' : null };
export interface Visitor {
  'status' : string,
  'accessCardReturned' : boolean,
  'accessCardNumber' : [] | [string],
  'arrivalTime' : bigint,
  'departureTime' : [] | [bigint],
  'host' : string,
  'name' : string,
  'createdAt' : bigint,
  'visitorId' : string,
  'badgeExpired' : boolean,
  'company' : string,
  'idNumber' : string,
  'badgeQr' : string,
  'notes' : string,
  'category' : string,
  'phone' : string,
  'department' : string,
  'purpose' : string,
  'companyId' : string,
}
export interface _SERVICE {
  'addBlacklistEntry' : ActorMethod<[BlacklistEntry], undefined>,
  'deleteAppointment' : ActorMethod<[string, string], undefined>,
  'getAppointments' : ActorMethod<[string], Array<Appointment>>,
  'getBlacklist' : ActorMethod<[string], Array<BlacklistEntry>>,
  'getCompanyById' : ActorMethod<[string], [] | [Company]>,
  'getStaffByCompanyId' : ActorMethod<[string], Array<Staff>>,
  'getVisitors' : ActorMethod<[string], Array<Visitor>>,
  'loginCompany' : ActorMethod<[string], [] | [Company]>,
  'loginStaff' : ActorMethod<[string, string], [] | [Staff]>,
  'registerCompany' : ActorMethod<
    [string, string, string, string, string, string],
    Company
  >,
  'registerStaff' : ActorMethod<[string, string, string, StaffRole], Staff>,
  'removeBlacklistEntry' : ActorMethod<[string, string], undefined>,
  'saveAppointment' : ActorMethod<[Appointment], undefined>,
  'saveVisitor' : ActorMethod<[Visitor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];