/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlacklistEntry = IDL.Record({
  'name' : IDL.Text,
  'idNumber' : IDL.Text,
  'addedAt' : IDL.Int,
  'addedBy' : IDL.Text,
  'category' : IDL.Text,
  'reason' : IDL.Text,
  'companyId' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const HostApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Text,
  'status' : AppointmentStatus,
  'noShow' : IDL.Bool,
  'hostName' : IDL.Text,
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'hostStaffId' : IDL.Text,
  'hostApprovalStatus' : HostApprovalStatus,
  'appointmentDate' : IDL.Int,
  'meetingRoomId' : IDL.Text,
  'visitorId' : IDL.Text,
  'appointmentTime' : IDL.Text,
  'visitorName' : IDL.Text,
  'notes' : IDL.Text,
  'purpose' : IDL.Text,
  'companyId' : IDL.Text,
});
export const Company = IDL.Record({
  'loginCode' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sector' : IDL.Text,
  'address' : IDL.Text,
  'authorizedPerson' : IDL.Text,
  'companyId' : IDL.Text,
});
export const StaffRole = IDL.Variant({
  'admin' : IDL.Null,
  'security' : IDL.Null,
});
export const Staff = IDL.Record({
  'staffId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : StaffRole,
  'companyId' : IDL.Text,
});
export const Visitor = IDL.Record({
  'status' : IDL.Text,
  'accessCardReturned' : IDL.Bool,
  'accessCardNumber' : IDL.Opt(IDL.Text),
  'arrivalTime' : IDL.Int,
  'departureTime' : IDL.Opt(IDL.Int),
  'host' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'visitorId' : IDL.Text,
  'badgeExpired' : IDL.Bool,
  'company' : IDL.Text,
  'idNumber' : IDL.Text,
  'badgeQr' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'purpose' : IDL.Text,
  'companyId' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlacklistEntry' : IDL.Func([BlacklistEntry], [], []),
  'deleteAppointment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAppointments' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], ['query']),
  'getBlacklist' : IDL.Func([IDL.Text], [IDL.Vec(BlacklistEntry)], ['query']),
  'getCompanyById' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'getStaffByCompanyId' : IDL.Func([IDL.Text], [IDL.Vec(Staff)], ['query']),
  'getVisitors' : IDL.Func([IDL.Text], [IDL.Vec(Visitor)], ['query']),
  'loginCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'loginStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Staff)], ['query']),
  'registerCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Company],
      [],
    ),
  'registerStaff' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, StaffRole],
      [Staff],
      [],
    ),
  'removeBlacklistEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveAppointment' : IDL.Func([Appointment], [], []),
  'saveVisitor' : IDL.Func([Visitor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlacklistEntry = IDL.Record({
    'name' : IDL.Text,
    'idNumber' : IDL.Text,
    'addedAt' : IDL.Int,
    'addedBy' : IDL.Text,
    'category' : IDL.Text,
    'reason' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const HostApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Text,
    'status' : AppointmentStatus,
    'noShow' : IDL.Bool,
    'hostName' : IDL.Text,
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'hostStaffId' : IDL.Text,
    'hostApprovalStatus' : HostApprovalStatus,
    'appointmentDate' : IDL.Int,
    'meetingRoomId' : IDL.Text,
    'visitorId' : IDL.Text,
    'appointmentTime' : IDL.Text,
    'visitorName' : IDL.Text,
    'notes' : IDL.Text,
    'purpose' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const Company = IDL.Record({
    'loginCode' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sector' : IDL.Text,
    'address' : IDL.Text,
    'authorizedPerson' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const StaffRole = IDL.Variant({ 'admin' : IDL.Null, 'security' : IDL.Null });
  const Staff = IDL.Record({
    'staffId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : StaffRole,
    'companyId' : IDL.Text,
  });
  const Visitor = IDL.Record({
    'status' : IDL.Text,
    'accessCardReturned' : IDL.Bool,
    'accessCardNumber' : IDL.Opt(IDL.Text),
    'arrivalTime' : IDL.Int,
    'departureTime' : IDL.Opt(IDL.Int),
    'host' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'visitorId' : IDL.Text,
    'badgeExpired' : IDL.Bool,
    'company' : IDL.Text,
    'idNumber' : IDL.Text,
    'badgeQr' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'purpose' : IDL.Text,
    'companyId' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlacklistEntry' : IDL.Func([BlacklistEntry], [], []),
    'deleteAppointment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAppointments' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], ['query']),
    'getBlacklist' : IDL.Func([IDL.Text], [IDL.Vec(BlacklistEntry)], ['query']),
    'getCompanyById' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'getStaffByCompanyId' : IDL.Func([IDL.Text], [IDL.Vec(Staff)], ['query']),
    'getVisitors' : IDL.Func([IDL.Text], [IDL.Vec(Visitor)], ['query']),
    'loginCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'loginStaff' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(Staff)], ['query']),
    'registerCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Company],
        [],
      ),
    'registerStaff' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, StaffRole],
        [Staff],
        [],
      ),
    'removeBlacklistEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveAppointment' : IDL.Func([Appointment], [], []),
    'saveVisitor' : IDL.Func([Visitor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };