/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlacklistEntry {
    name: string;
    idNumber: string;
    addedAt: bigint;
    addedBy: string;
    category: string;
    reason: string;
    companyId: string;
}
export interface Staff {
    staffId: string;
    name: string;
    createdAt: bigint;
    role: StaffRole;
    companyId: string;
}
export interface Visitor {
    status: string;
    accessCardReturned: boolean;
    accessCardNumber?: string;
    arrivalTime: bigint;
    departureTime?: bigint;
    host: string;
    name: string;
    createdAt: bigint;
    visitorId: string;
    badgeExpired: boolean;
    company: string;
    idNumber: string;
    badgeQr: string;
    notes: string;
    category: string;
    phone: string;
    department: string;
    purpose: string;
    companyId: string;
}
export interface Appointment {
    id: string;
    status: AppointmentStatus;
    noShow: boolean;
    hostName: string;
    createdAt: bigint;
    createdBy: string;
    hostStaffId: string;
    hostApprovalStatus: HostApprovalStatus;
    appointmentDate: bigint;
    meetingRoomId: string;
    visitorId: string;
    appointmentTime: string;
    visitorName: string;
    notes: string;
    purpose: string;
    companyId: string;
}
export interface Company {
    loginCode: string;
    name: string;
    createdAt: bigint;
    sector: string;
    address: string;
    authorizedPerson: string;
    companyId: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    approved = "approved"
}
export enum HostApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum StaffRole {
    admin = "admin",
    security = "security"
}
export interface backendInterface {
    addBlacklistEntry(entry: BlacklistEntry): Promise<void>;
    deleteAppointment(companyId: string, appointmentId: string): Promise<void>;
    getAppointments(companyId: string): Promise<Array<Appointment>>;
    getBlacklist(companyId: string): Promise<Array<BlacklistEntry>>;
    getCompanyById(companyId: string): Promise<Company | null>;
    getStaffByCompanyId(companyId: string): Promise<Array<Staff>>;
    getVisitors(companyId: string): Promise<Array<Visitor>>;
    loginCompany(loginCode: string): Promise<Company | null>;
    loginStaff(staffId: string, companyId: string): Promise<Staff | null>;
    registerCompany(companyId: string, loginCode: string, name: string, sector: string, address: string, authorizedPerson: string): Promise<Company>;
    registerStaff(staffId: string, companyId: string, name: string, role: StaffRole): Promise<Staff>;
    removeBlacklistEntry(companyId: string, idNumber: string): Promise<void>;
    saveAppointment(appointment: Appointment): Promise<void>;
    saveVisitor(v: Visitor): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, Company as _Company, HostApprovalStatus as _HostApprovalStatus, Staff as _Staff, StaffRole as _StaffRole, Visitor as _Visitor } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlacklistEntry(arg0: BlacklistEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlacklistEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlacklistEntry(arg0);
            return result;
        }
    }
    async deleteAppointment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0, arg1);
            return result;
        }
    }
    async getAppointments(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlacklist(arg0: string): Promise<Array<BlacklistEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlacklist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlacklist(arg0);
            return result;
        }
    }
    async getCompanyById(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyById(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyById(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffByCompanyId(arg0: string): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffByCompanyId(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffByCompanyId(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisitors(arg0: string): Promise<Array<Visitor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitors(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitors(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginCompany(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginCompany(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginCompany(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginStaff(arg0: string, arg1: string): Promise<Staff | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginStaff(arg0, arg1);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginStaff(arg0, arg1);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCompany(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCompany(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCompany(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerStaff(arg0: string, arg1: string, arg2: string, arg3: StaffRole): Promise<Staff> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStaff(arg0, arg1, arg2, to_candid_StaffRole_n20(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Staff_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStaff(arg0, arg1, arg2, to_candid_StaffRole_n20(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Staff_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeBlacklistEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBlacklistEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBlacklistEntry(arg0, arg1);
            return result;
        }
    }
    async saveAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAppointment(to_candid_Appointment_n22(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAppointment(to_candid_Appointment_n22(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveVisitor(arg0: Visitor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVisitor(to_candid_Visitor_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVisitor(to_candid_Visitor_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_HostApprovalStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HostApprovalStatus): HostApprovalStatus {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StaffRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StaffRole): StaffRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Staff_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Staff): Staff {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Visitor_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visitor): Visitor {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Staff]): Staff | null {
    return value.length === 0 ? null : from_candid_Staff_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Company]): Company | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    staffId: string;
    name: string;
    createdAt: bigint;
    role: _StaffRole;
    companyId: string;
}): {
    staffId: string;
    name: string;
    createdAt: bigint;
    role: StaffRole;
    companyId: string;
} {
    return {
        staffId: value.staffId,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_StaffRole_n12(_uploadFile, _downloadFile, value.role),
        companyId: value.companyId
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    accessCardReturned: boolean;
    accessCardNumber: [] | [string];
    arrivalTime: bigint;
    departureTime: [] | [bigint];
    host: string;
    name: string;
    createdAt: bigint;
    visitorId: string;
    badgeExpired: boolean;
    company: string;
    idNumber: string;
    badgeQr: string;
    notes: string;
    category: string;
    phone: string;
    department: string;
    purpose: string;
    companyId: string;
}): {
    status: string;
    accessCardReturned: boolean;
    accessCardNumber?: string;
    arrivalTime: bigint;
    departureTime?: bigint;
    host: string;
    name: string;
    createdAt: bigint;
    visitorId: string;
    badgeExpired: boolean;
    company: string;
    idNumber: string;
    badgeQr: string;
    notes: string;
    category: string;
    phone: string;
    department: string;
    purpose: string;
    companyId: string;
} {
    return {
        status: value.status,
        accessCardReturned: value.accessCardReturned,
        accessCardNumber: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.accessCardNumber)),
        arrivalTime: value.arrivalTime,
        departureTime: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.departureTime)),
        host: value.host,
        name: value.name,
        createdAt: value.createdAt,
        visitorId: value.visitorId,
        badgeExpired: value.badgeExpired,
        company: value.company,
        idNumber: value.idNumber,
        badgeQr: value.badgeQr,
        notes: value.notes,
        category: value.category,
        phone: value.phone,
        department: value.department,
        purpose: value.purpose,
        companyId: value.companyId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _AppointmentStatus;
    noShow: boolean;
    hostName: string;
    createdAt: bigint;
    createdBy: string;
    hostStaffId: string;
    hostApprovalStatus: _HostApprovalStatus;
    appointmentDate: bigint;
    meetingRoomId: string;
    visitorId: string;
    appointmentTime: string;
    visitorName: string;
    notes: string;
    purpose: string;
    companyId: string;
}): {
    id: string;
    status: AppointmentStatus;
    noShow: boolean;
    hostName: string;
    createdAt: bigint;
    createdBy: string;
    hostStaffId: string;
    hostApprovalStatus: HostApprovalStatus;
    appointmentDate: bigint;
    meetingRoomId: string;
    visitorId: string;
    appointmentTime: string;
    visitorName: string;
    notes: string;
    purpose: string;
    companyId: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n4(_uploadFile, _downloadFile, value.status),
        noShow: value.noShow,
        hostName: value.hostName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        hostStaffId: value.hostStaffId,
        hostApprovalStatus: from_candid_HostApprovalStatus_n6(_uploadFile, _downloadFile, value.hostApprovalStatus),
        appointmentDate: value.appointmentDate,
        meetingRoomId: value.meetingRoomId,
        visitorId: value.visitorId,
        appointmentTime: value.appointmentTime,
        visitorName: value.visitorName,
        notes: value.notes,
        purpose: value.purpose,
        companyId: value.companyId
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    security: null;
}): StaffRole {
    return "admin" in value ? StaffRole.admin : "security" in value ? StaffRole.security : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "approved" in value ? AppointmentStatus.approved : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): HostApprovalStatus {
    return "pending" in value ? HostApprovalStatus.pending : "approved" in value ? HostApprovalStatus.approved : "rejected" in value ? HostApprovalStatus.rejected : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Visitor>): Array<Visitor> {
    return value.map((x)=>from_candid_Visitor_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Staff>): Array<Staff> {
    return value.map((x)=>from_candid_Staff_n10(_uploadFile, _downloadFile, x));
}
function to_candid_AppointmentStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_HostApprovalStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HostApprovalStatus): _HostApprovalStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_StaffRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): _StaffRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Visitor_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visitor): _Visitor {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: AppointmentStatus;
    noShow: boolean;
    hostName: string;
    createdAt: bigint;
    createdBy: string;
    hostStaffId: string;
    hostApprovalStatus: HostApprovalStatus;
    appointmentDate: bigint;
    meetingRoomId: string;
    visitorId: string;
    appointmentTime: string;
    visitorName: string;
    notes: string;
    purpose: string;
    companyId: string;
}): {
    id: string;
    status: _AppointmentStatus;
    noShow: boolean;
    hostName: string;
    createdAt: bigint;
    createdBy: string;
    hostStaffId: string;
    hostApprovalStatus: _HostApprovalStatus;
    appointmentDate: bigint;
    meetingRoomId: string;
    visitorId: string;
    appointmentTime: string;
    visitorName: string;
    notes: string;
    purpose: string;
    companyId: string;
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n24(_uploadFile, _downloadFile, value.status),
        noShow: value.noShow,
        hostName: value.hostName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        hostStaffId: value.hostStaffId,
        hostApprovalStatus: to_candid_HostApprovalStatus_n26(_uploadFile, _downloadFile, value.hostApprovalStatus),
        appointmentDate: value.appointmentDate,
        meetingRoomId: value.meetingRoomId,
        visitorId: value.visitorId,
        appointmentTime: value.appointmentTime,
        visitorName: value.visitorName,
        notes: value.notes,
        purpose: value.purpose,
        companyId: value.companyId
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    accessCardReturned: boolean;
    accessCardNumber?: string;
    arrivalTime: bigint;
    departureTime?: bigint;
    host: string;
    name: string;
    createdAt: bigint;
    visitorId: string;
    badgeExpired: boolean;
    company: string;
    idNumber: string;
    badgeQr: string;
    notes: string;
    category: string;
    phone: string;
    department: string;
    purpose: string;
    companyId: string;
}): {
    status: string;
    accessCardReturned: boolean;
    accessCardNumber: [] | [string];
    arrivalTime: bigint;
    departureTime: [] | [bigint];
    host: string;
    name: string;
    createdAt: bigint;
    visitorId: string;
    badgeExpired: boolean;
    company: string;
    idNumber: string;
    badgeQr: string;
    notes: string;
    category: string;
    phone: string;
    department: string;
    purpose: string;
    companyId: string;
} {
    return {
        status: value.status,
        accessCardReturned: value.accessCardReturned,
        accessCardNumber: value.accessCardNumber ? candid_some(value.accessCardNumber) : candid_none(),
        arrivalTime: value.arrivalTime,
        departureTime: value.departureTime ? candid_some(value.departureTime) : candid_none(),
        host: value.host,
        name: value.name,
        createdAt: value.createdAt,
        visitorId: value.visitorId,
        badgeExpired: value.badgeExpired,
        company: value.company,
        idNumber: value.idNumber,
        badgeQr: value.badgeQr,
        notes: value.notes,
        category: value.category,
        phone: value.phone,
        department: value.department,
        purpose: value.purpose,
        companyId: value.companyId
    };
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StaffRole): {
    admin: null;
} | {
    security: null;
} {
    return value == StaffRole.admin ? {
        admin: null
    } : value == StaffRole.security ? {
        security: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    approved: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HostApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == HostApprovalStatus.pending ? {
        pending: null
    } : value == HostApprovalStatus.approved ? {
        approved: null
    } : value == HostApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
